name: CI

on:
  push:
  pull_request:
    branches:
      - main
      - staging

jobs:
  build:
    name: build-app 

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B clean install -DskipTests
